version: "3.8"

services:
  web:
    container_name: example
    build: .
    ports:
      - "5000:3000"
    environment:
      - PGDATABASE=appledb
      - PGUSER=yared
      - PGPASSWORD=1234
      - PGHOST=postgresql
    links:
      - postgresql
    volumes:
      - .:/usr/src/app
  postgresql:
    container_name: postdatabases
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=yared
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=appledb
    volumes:
      - ~/docker/postgres:/var/lib/postgresql/data
