version: "3.1"

services:
  web:
    container_name: example
    build: .
    ports:
      - "4000:3000"
    environment:
      - MYSQL_USER=yared
      - MYSQL_PASSWORD=9514
      - MYSQL_DATABASE=appledb
      - MYSQL_HOST=mysqlmanito
      - JWT_SECRET=Holsdj28397kjHd7@asdyui3897k
    links:
      - mysql
    volumes:
      - .:/usr/src/app
  mysql:
    container_name: mysqldatabase
    image: mysql:latest
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=9514
      - MYSQL_DATABASE=appledb
      - MYSQL_USER=yared
      - MYSQL_PASSWORD=9514
    volumes:
      - ~/docker/mysql:/var/lib/mysql
