/*
 Navicat Premium Data Transfer

 Source Server         : yared
 Source Server Type    : PostgreSQL
 Source Server Version : 140002
 Source Host           : localhost:5432
 Source Catalog        : applelabs
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 140002
 File Encoding         : 65001

 Date: 11/05/2022 14:05:13
*/


-- ----------------------------
-- Table structure for horario_empleado
-- ----------------------------
DROP TABLE IF EXISTS "public"."horario_empleado";
CREATE TABLE "public"."horario_empleado" (
  "id_horario" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
),
  "id_user" int2,
  "fecha_hora" timestamp(6),
  "tipo_asistencia" varchar(16) COLLATE "pg_catalog"."default",
  "id_horario_general" int2
)
;

-- ----------------------------
-- Table structure for horario_general
-- ----------------------------
DROP TABLE IF EXISTS "public"."horario_general";
CREATE TABLE "public"."horario_general" (
  "id_horario_general" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
),
  "hora_entrada" varchar(100) COLLATE "pg_catalog"."default",
  "hora_salida" varchar(100) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for jobs
-- ----------------------------
DROP TABLE IF EXISTS "public"."jobs";
CREATE TABLE "public"."jobs" (
  "idjobs" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
),
  "id_user" int2,
  "idproduct" int2,
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "model" varchar(255) COLLATE "pg_catalog"."default",
  "phone_number" int4,
  "description" varchar(255) COLLATE "pg_catalog"."default",
  "price" int8,
  "priority" varchar(255) COLLATE "pg_catalog"."default",
  "estate" bool,
  "date" timestamp(0)
)
;
COMMENT ON COLUMN "public"."jobs"."priority" IS 'baja,media,alta';

-- ----------------------------
-- Table structure for pagos_diarios
-- ----------------------------
DROP TABLE IF EXISTS "public"."pagos_diarios";
CREATE TABLE "public"."pagos_diarios" (
  "id_pagosdiarios" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
),
  "id_users" int2,
  "fecha" date,
  "monto" int4
)
;

-- ----------------------------
-- Table structure for products
-- ----------------------------
DROP TABLE IF EXISTS "public"."products";
CREATE TABLE "public"."products" (
  "idproduct" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
),
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "cant" int8,
  "price" float4,
  "img" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS "public"."users";
CREATE TABLE "public"."users" (
  "id_user" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
),
  "email" varchar(255) COLLATE "pg_catalog"."default",
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "password" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "role" varchar COLLATE "pg_catalog"."default",
  "img" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Primary Key structure for table horario_empleado
-- ----------------------------
ALTER TABLE "public"."horario_empleado" ADD CONSTRAINT "horario_pkey" PRIMARY KEY ("id_horario");

-- ----------------------------
-- Primary Key structure for table horario_general
-- ----------------------------
ALTER TABLE "public"."horario_general" ADD CONSTRAINT "horario_general_pkey" PRIMARY KEY ("id_horario_general");

-- ----------------------------
-- Primary Key structure for table jobs
-- ----------------------------
ALTER TABLE "public"."jobs" ADD CONSTRAINT "trabajos_pkey" PRIMARY KEY ("idjobs");

-- ----------------------------
-- Primary Key structure for table pagos_diarios
-- ----------------------------
ALTER TABLE "public"."pagos_diarios" ADD CONSTRAINT "pagosdiarios_pkey" PRIMARY KEY ("id_pagosdiarios");

-- ----------------------------
-- Primary Key structure for table products
-- ----------------------------
ALTER TABLE "public"."products" ADD CONSTRAINT "products_pkey" PRIMARY KEY ("idproduct");

-- ----------------------------
-- Primary Key structure for table users
-- ----------------------------
ALTER TABLE "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id_user");
