-- ----------------------------
-- Table structure for horario_empleado
-- ----------------------------
DROP TABLE IF EXISTS "public"."horario_empleado";
CREATE TABLE "public"."horario_empleado" (
  "id_horario" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE  1
    MAXVALUE 32767
    START 1
    ),
  "id_user" int2,
  "fecha_hora" timestamp(6),
  "tipo_asistencia" varchar(16) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for horario_general
-- ----------------------------
DROP TABLE IF EXISTS "public"."horario_general";
CREATE TABLE "public"."horario_general" (
  "id_horario_general" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
),
  "hora_entrada" varchar(100) COLLATE "pg_catalog"."default",
  "hora_salida" varchar(100) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for jobs
-- ----------------------------
DROP TABLE IF EXISTS "public"."jobs";
CREATE TABLE "public"."jobs" (
  "idtrabajos" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
),
  "iduser" int2,
  "idproductos" int2,
  "name " varchar(255) COLLATE "pg_catalog"."default",
  "model" varchar(255) COLLATE "pg_catalog"."default",
  "phone_number" int4,
  "description" varchar(255) COLLATE "pg_catalog"."default",
  "price" int8,
  "priority" varchar(255) COLLATE "pg_catalog"."default",
  "estate" bool,
  "date" timestamp(6)
)
;
COMMENT ON COLUMN "public"."jobs"."priority" IS 'baja,media,alta';

-- ----------------------------
-- Table structure for pagos_diarios
-- ----------------------------
DROP TABLE IF EXISTS "public"."pagos_diarios";
CREATE TABLE "public"."pagos_diarios" (
  "id_pagosdiarios" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
),
  "id_users" int2,
  "fecha" date,
  "monto" int4
)
;

-- ----------------------------
-- Table structure for products
-- ----------------------------
DROP TABLE IF EXISTS "public"."products";
CREATE TABLE "public"."products" (
  "idproducto" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
),
  "idtrabajos " int2,
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "cant" int8,
  "sold" bool
)
;

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS "public"."users";
CREATE TABLE "public"."users" (
  "iduser" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
),
  "email" varchar(255) COLLATE "pg_catalog"."default",
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "password" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "role" varchar COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Primary Key structure for table horario_empleado
-- ----------------------------
ALTER TABLE "public"."horario_empleado" ADD CONSTRAINT "horario_pkey" PRIMARY KEY ("id_horario");

-- ----------------------------
-- Primary Key structure for table horario_general
-- ----------------------------
ALTER TABLE "public"."horario_general" ADD CONSTRAINT "horario_general_pkey" PRIMARY KEY ("id_horario_general");

-- ----------------------------
-- Primary Key structure for table jobs
-- ----------------------------
ALTER TABLE "public"."jobs" ADD CONSTRAINT "trabajos_pkey" PRIMARY KEY ("idtrabajos");

-- ----------------------------
-- Primary Key structure for table pagos_diarios
-- ----------------------------
ALTER TABLE "public"."pagos_diarios" ADD CONSTRAINT "pagosdiarios_pkey" PRIMARY KEY ("id_pagosdiarios");

-- ----------------------------
-- Primary Key structure for table products
-- ----------------------------
ALTER TABLE "public"."products" ADD CONSTRAINT "products_pkey" PRIMARY KEY ("idproducto");

-- ----------------------------
-- Primary Key structure for table users
-- ----------------------------
ALTER TABLE "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("iduser");
